### ISSUE TITLE
Ex. 4.1

### ISSUE THREAD

**Issue by telemachus** [cutajarj/ConcurrentProgrammingWithGo#2]
Maybe you're aware of this (and maybe it's intentional for a lesson later), but the solution here for exercise 4.1 still has a data race. (The `count` variable is read in the condition at the top of the `for` loop, and nothing protects that read.)

Something like the following fixes the remaining data race but feels weird overall. (Maybe that's just a function of this being an exercise without a larger program for background.)

```go
package main

import (
	"fmt"
	"sync"
	"time"
)

func countdown(seconds *int, mutex *sync.Mutex) {
	mutex.Lock()
	remaining := *seconds
	mutex.Unlock()
	for remaining > 0 {
		time.Sleep(1 * time.Second)
		mutex.Lock()
		*seconds -= 1
		remaining = *seconds
		mutex.Unlock()
	}
}

func main() {
	mutex := sync.Mutex{}
	count := 5
	i := count
	go countdown(&count, &mutex)
	for i > 0 {
		time.Sleep(500 * time.Millisecond)
		mutex.Lock()
		fmt.Println(count)
		i = count
		mutex.Unlock()
	}
}
```

**Comment by cutajarj2** [comment]
Thank you for spotting this. This is proof that race conditions are easy to miss! I have just pushed an update, similar to what you suggest.

It does feels weird to do this type of synchronisation. It's much better to use channels for this type of scenario, however the channels are later in the book. At this point in the book I wanted to challenge the reader to think about copying the shared variable instead of reading it directly.

**Comment by guneyizol** [comment]
Hello
I believe there is still a race condition. I think the best solution is printing the loop variable (`i` in the above program) instead of printing the shared `count` variable.
